services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: textapp_web
    env_file: ./app/.env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: python -m app.app

  worker:
    build: .
    container_name: textapp_worker
    env_file: ./app/.env
    depends_on:
      - redis
    command: celery -A app.tasks worker --loglevel=info
